SQL: forced versioning global variables [closes #32]
tempesta-tech/mariadb pull request #149
Opened 2017-03-08 10:13 UTC by kevgs

Set variables like this:
./mtr --mem --suite=main --mysqld='--force-versioning=1' --mysqld='--force-hidden=1'

2017-03-09 05:19 UTC, midenok commented
Wrong base.

2017-03-09 13:31 UTC, midenok requested changes
Please add plugin files, make `hide_versioning` bool, etc (see comments).

2017-03-09 13:31 UTC, midenok commented on sql/sys_vars.cc
> +       "force_versioning", "Makes all creating tables versioned by default",
"Force System Versioning for all created tables"

2017-03-09 13:31 UTC, midenok commented on sql/sys_vars.cc
> +       "force_hidden", "Make versioning info hidden from everything "
Sys_hide_versioning
"hide_versioning", "Hide System Versioning from being displayed in table info"

2017-03-09 13:31 UTC, midenok commented on sql/sys_vars.cc
> +       "(2 - not specified, 0 - not hidden, 1 - hidden)",
2: needless for user. Should be ON/OFF.

2017-03-09 13:39 UTC, kevgs commented on sql/sys_vars.cc
> +       "(2 - not specified, 0 - not hidden, 1 - hidden)",
It's not useful. If you not specify `force_hidden` and specify `force_versioning` you'll get versioning + hidden. If we make this `bool` we'll need to specify both flags to achieve same effect.

2017-03-09 13:39 UTC, kevgs commented
What plugin should do?

2017-03-10 02:42 UTC, midenok commented on sql/sys_vars.cc
> +       "(2 - not specified, 0 - not hidden, 1 - hidden)",
You display internal mechansims to UI. Will **2** be ever used by user??

2017-03-10 02:43 UTC, midenok commented
What it does now in `am/forced_vers`.

2017-03-10 03:27 UTC, midenok commented
I'll finish it.

2017-03-10 03:27 UTC, closed without merging