SQL: CREATE VIEW and misc improvements [fixes #183]
tempesta-tech/mariadb pull request #184
Opened 2017-04-25 12:13 UTC by midenok

Please, review.

2017-04-25 12:36 UTC, kevgs commented on sql/sql_lex.cc
> +      table->alias, field_name, field_name);
Maybe use `buf` instead of a second `field_name` here?

2017-04-25 13:04 UTC, kevgs commented on sql/sql_view.cc
> +      bool add_start= true;
You do not check order of system field here while it's necessary.
```sql
select *, sys_trx_start, sys_trx_end from vt;
```

2017-04-25 13:05 UTC, midenok commented on sql/sql_lex.cc
> +      table->alias, field_name, field_name);
Did you read `WARN_VERS_ALIAS_TOO_LONG` message? How will it look?

2017-04-25 13:05 UTC, kevgs requested changes
Add vers fields position check at `create view`.

2017-04-25 13:05 UTC, midenok commented on sql/sql_view.cc
> +      bool add_start= true;
Why it is neccessary?

2017-04-25 13:09 UTC, kevgs commented on sql/sql_view.cc
> +      bool add_start= true;
Try this test case. `SELECTS` returns nothing here, while it should return 1 row.
```sql
create table t (a int) with system versioning;
insert into t values (1);
create view vt as select a, sys_trx_end, sys_trx_start from t;
select *, sys_trx_start, sys_trx_end from vt;
```

Our code relies on particular vers field position and order. As I understand, standard requires it too.

2017-04-25 13:14 UTC, midenok commented on sql/sql_view.cc
> +      bool add_start= true;
Did you put order dependency somewhere?

2017-04-25 13:26 UTC, kevgs commented on sql/sql_view.cc
> +      bool add_start= true;
Here it is. https://github.com/tempesta-tech/mariadb_10.2/commit/5a6844c927af6fd3798e2fe146dcffd062426d57#diff-baac2b2856d07d7828e3890b8eb9d217R16949

2017-04-25 13:36 UTC, midenok commented on sql/sql_view.cc
> +      bool add_start= true;
Fixed.

2017-04-25 14:10 UTC, kevgs commented on sql/sql_lex.cc
> +      table->alias, field_name, field_name);
All works fine. I suggest to add this test case:
```sql
create table t (a int) with system versioning;
create view vt as select a from t as longlonglonglonglonglonglonglong;
show create view vt;
```

2017-04-25 14:15 UTC, kevgs commented on sql/sql_view.cc
> +      bool add_start= true;
I suggest to add a test case:
```sql
create table t (a int) with system versioning;
insert into t values (1);
update t set a=2;
create view vt as select a, sys_trx_end, sys_trx_start from t for system_time all;
select * from vt;
```

2017-04-25 14:16 UTC, kevgs approved these changes

2017-04-25 20:05 UTC, midenok commented on sql/sql_lex.cc
> +      table->alias, field_name, field_name);
There are such test cases. Look for 'baba'.

2017-04-26 14:07 UTC, midenok commented
Please, review again. Diff between old and new versions:
```
git diff am/183-multi_sysfield am/trunk
```

2017-04-26 18:49 UTC, kevgs commented on sql/sql_view.cc
> +    TABLE_LIST *impli_table= NULL, *expli_table= NULL;
IMO `implicit_table` and `explicit_table` looks better.

2017-04-26 18:50 UTC, kevgs commented on sql/sql_view.cc
> +        Item_field *fld= (Item_field*) (item->real_item());
Extra parentheses.

2017-04-26 19:06 UTC, merged