Scripts: innodb_vtd table [closes #122]
tempesta-tech/mariadb pull request #190
Opened 2017-05-12 10:09 UTC by kevgs

Just one primary index because I don't know access pattern to this table.

2017-05-15 08:03 UTC, midenok requested changes
Full test failures. See build 68 on Sunny.

2017-05-15 17:10 UTC, midenok commented
Will upgrade work from older version?

2017-05-17 07:08 UTC, midenok commented
Rename `innodb_vtd` to `vtmd`.

2017-05-17 17:33 UTC, midenok requested changes
Remove `trx_id_end` from clustered index and fix minor notes. Run full test on Sunny.

2017-05-17 17:33 UTC, midenok commented on scripts/mysql_system_tables_fix.sql
> +) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin STATS_PERSISTENT=0";
Do we have to duplicate creation command?

2017-05-17 17:33 UTC, midenok commented on mysql-test/r/1st.result
>  time_zone_transition
Abbreviations are written in all caps in commit messages.

2017-05-17 17:33 UTC, midenok commented on scripts/mysql_system_tables.sql
> +	PRIMARY KEY(trx_id_start, trx_id_end, name)
Don't need `trx_id_end` in PK. Read about [Multiple column index vs multiple indexes](https://www.percona.com/blog/2014/01/03/multiple-column-index-vs-multiple-indexes-with-mysql-56/) to know better on the topic.

2017-05-17 17:44 UTC, midenok commented on scripts/mysql_system_tables.sql
> +	PRIMARY KEY(trx_id_start, trx_id_end, name)
Please, comment each column.

2017-05-18 05:50 UTC, midenok commented
Rename `trx_id_start` to `start`, `trx_id_end` to `end`. Make VTMD versioned table by period (start, end).

2017-05-18 08:59 UTC, kevgs commented
>  Will upgrade work from older version?

Yes, it will.

> Rename innodb_vtd to vtmd.

Done.

> Remove trx_id_end from clustered index and fix minor notes. Run full test on Sunny.

> Do we have to duplicate creation command?

Actually not, because `mysql_system_tables.sql` and `mysql_system_tables_fix.sql` got concatenated in a single `mysql_fix_privilege_tables.sql` which is used by `mysql_upgrade`

> Abbreviations are written in all caps in commit messages.

Done.

> Don't need trx_id_end in PK.

Done.

> Please, comment each column.

Done.

> Rename trx_id_start to start, trx_id_end to end. Make VTMD versioned table by period (start, end).

Done.


Currently waiting for sunny.

2017-05-18 09:04 UTC, midenok commented
Comments are marked by `COMMENT` clause, not by #-sign.

2017-05-18 09:24 UTC, kevgs commented
Columns with `GENERATED ALWAYS AS ROW START/END` do not support `COMMENT 'asdf'`.

2017-05-18 09:27 UTC, midenok commented
VTMD is not created on start. Did you test upgrade?

2017-05-18 09:29 UTC, midenok commented
> Columns with GENERATED ALWAYS AS ROW START/END do not support COMMENT 'asdf'.

Why?

2017-05-18 11:14 UTC, kevgs commented
For my `VTMD` is created by both `mysql_install_db` and `mysql_upgrade`. How did you tested it?

> > Columns with GENERATED ALWAYS AS ROW START/END do not support COMMENT 'asdf'.
> Why?
It's not implemented in sql/sql_yacc.yy. Looks like a miss feature.

2017-05-18 11:44 UTC, midenok commented
> It's not implemented in sql/sql_yacc.yy. Looks like a miss feature.

It's just a bug. Fix it.

2017-05-19 07:50 UTC, midenok approved these changes
Fix comments, rename table, remove `old_name`, make `frm_image` NOT NULL and merge. Don't forget to rerun main suite.

2017-05-19 07:50 UTC, midenok commented on mysql-test/suite/versioning/r/ddl.result
> +  `start` bigint(20) unsigned GENERATED ALWAYS AS ROW START COMMENT 'transaction which created table',
TRX_ID of table lifetime start

2017-05-19 07:50 UTC, midenok commented on mysql-test/suite/versioning/r/ddl.result
> +  `end` bigint(20) unsigned GENERATED ALWAYS AS ROW END COMMENT 'transaction which altered table',
TRX_ID of table lifetime end

2017-05-19 07:50 UTC, midenok commented on mysql-test/suite/versioning/r/ddl.result
> +  `name` varchar(64) COLLATE utf8_bin NOT NULL COMMENT 'current table name',
Table structure during period [start, end)

2017-05-19 07:50 UTC, midenok commented on mysql-test/suite/versioning/r/ddl.result
> +  `frm_image` blob DEFAULT NULL COMMENT '.frm file contents',
Table structure during period [start, end)
Make NOT NULL

2017-05-19 07:50 UTC, midenok commented on mysql-test/suite/versioning/r/ddl.result
> +  `col_renames` blob DEFAULT NULL COMMENT 'column rename mappings',
Column name mapping from previous lifetime

2017-05-19 07:50 UTC, midenok commented on mysql-test/suite/versioning/r/ddl.result
> +  `old_name` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT 'old table name if it was renamed',
Remove this column.

2017-05-19 07:50 UTC, midenok commented on mysql-test/suite/versioning/r/ddl.result
> +vtmd	CREATE TABLE `vtmd` (
Rename to `vtmd_template`.

2017-05-19 12:38 UTC, kevgs commented
`innodb.log_data_file_size` do not pass without some `PRIMARY KEY` on `vtmp_template`. Adding key on (start, end).

2017-05-19 13:26 UTC, midenok commented
Why do you make such strange PK? Make it on (end).

2017-05-21 14:53 UTC, merged