SQL: DROP sys_trx_* fields makes them hidden [closes #210)
tempesta-tech/mariadb pull request #215
Opened 2017-06-26 19:06 UTC by kevgs

Actually, does not change `SHOW CREATE TABLE`.

2017-06-26 20:35 UTC, midenok commented on sql/handler.cc
> +    return true;
Unreadable formatting.

2017-06-26 20:37 UTC, midenok commented on sql/handler.cc
> +          return true;
Same here.  Remove needless new-lines.

2017-06-26 20:39 UTC, midenok commented on sql/handler.cc
> +                    name);
Seriously? New-line just for `name`?

2017-06-26 20:41 UTC, midenok commented
Fix commit message.

2017-06-27 09:37 UTC, kevgs commented
> Fix commit message.

Copy PR name or use another one when 'Squash and merge'.

2017-06-27 11:09 UTC, midenok requested changes

2017-06-27 11:09 UTC, midenok commented on sql/handler.cc
> +            make_hidden(thd, alter_info, integer_fields, name, share, true))
`make_hidden()` is just another call, so don't spawn stubs. Use:
```c++
Field *f= NULL;
if (!done_start && is_trx_start(d->name))
{
  f= s->vers_start_field();
  done_start= true;
}
else if (!done_end && is_trx_end(d->name))
{
  f= s->vers_end_field();
  done_end= true;
}
else
  continue;
if (f->flags & HIDDEN_FLAG)
{
  // put real DROP error here (same when field is really missing).
}

// call vers_create_sys_field()

if (done_start && done_end)
  break;
```

2017-06-27 14:07 UTC, midenok commented on sql/handler.cc
> +                                  is_trx_start(name) ? VERS_SYS_START_FLAG
You already done `is_trx_start()` check. Why are you doing it again?

2017-06-27 16:56 UTC, midenok approved these changes

2017-06-27 17:59 UTC, merged