SQL: check TRANSACTION_REGISTRY table schema on start [closed #309]
tempesta-tech/mariadb pull request #312
Opened 2017-11-08 21:04 UTC by kevgs

Function (which is a place to check) is called in non-bootstrap mode:
```c++
  if (!opt_bootstrap)
    servers_init(0);
```

Check exists in `servers_init()` because we need `THD` to open a table. And this is one of places where `THD` created.

2017-11-08 21:50 UTC, midenok requested changes

2017-11-08 21:50 UTC, midenok commented on sql/sql_servers.cc
> +bool trt_table_correct(THD *thd, bool &correct)
Move to `TR_table::check()`. I don't see the reason why the code on opening the table should be duplicated.

2017-11-08 21:50 UTC, midenok commented on sql/sql_servers.cc
> +bool trt_table_type_is_correct(TABLE *t)
Don't see the reason why there is second function dedicated just for type checking.

2017-11-08 21:50 UTC, midenok commented on sql/sql_servers.cc
> +  if (trt_table_correct(thd, trt_correct))
This has nothing to do with `mysql.servers` table. Place schema check into `mysqld_main()` after `Events::init()` (mysqld.cc:6024). Make your own temporary `thd`.

2017-11-08 22:17 UTC, kevgs commented
3 notes fixed.

2017-11-10 07:55 UTC, midenok commented on sql/mysqld.cc
> +        exit(1);
Use `unireg_abort(1)`. It is good to free `thd` here as well.

2017-11-10 07:58 UTC, midenok commented on sql/table.cc
> +    return true;
Use `field_id_t`. Also check `FLD_ISO_LEVEL` for enum order.

2017-11-10 16:42 UTC, closed without merging