MDEV-16026: Global system_versioning_asof must not be used if client …
tempesta-tech/mariadb pull request #502
Opened 2018-06-13 17:41 UTC by FooBarrior

…sessions can have non-default time zone

* store `system_versioning_asof` as timestamp;
* session var processed in session timezone; global var processed in global timezone;
* if session var is `DEFAULT`, then global var is used;

As a regression, we cannot assign values below 1970 anymore

2018-06-14 05:32 UTC, midenok commented
Please, cleanup the patch.

2018-06-14 06:09 UTC, kevgs commented on sql/sql_select.cc
> +    thd->variables.time_zone->gmt_sec_to_TIME(&ltime, in.timestamp);
Global variable and session timezone. Is that ok?

2018-06-14 10:08 UTC, midenok requested changes

2018-06-14 10:08 UTC, midenok commented on sql/sql_select.cc
> +    vars = &global_system_variables;
That's not the way `global_system_variables` are used. Session variable must be used **always**. Global variable is used **only** when new session is created. I.e. session variable is initialized from global variable.

2018-06-15 08:39 UTC, midenok commented
2 things still not fixed:
1. commit message;
2. word typo (interfer).

2018-06-15 12:51 UTC, FooBarrior commented
done

2018-06-15 13:46 UTC, midenok approved these changes
Use "Squash and merge" to merge to trunk.

2018-06-18 14:58 UTC, merged