MDEV-17395 REPLACE/INSERT ODKU: support WITHOUT OVERLAPS
tempesta-tech/mariadb pull request #560
Opened 2018-12-03 14:35 UTC by FooBarrior

2018-12-14 20:18 UTC, midenok requested changes

2018-12-14 20:18 UTC, midenok commented on sql/sql_insert.cc
> +        error= table->file->ha_rnd_pos(table->record[1], table->file->dup_ref);
Don't reindent large blocks of old code by reorganizing goto, if forks, etc. This kind of refactoring (and anything that changes code outlook, but not the business logic) should be done in separate commits, but I doubt this one is a good idea.

2018-12-14 20:18 UTC, midenok commented on mysql-test/suite/period/t/insert_replace.test
> +drop table t;
1. Please, don't split test cases into many small files. This slows down MTR execution time substantially.

2. Only MyISAM is tested. It must test both engines. This will be fixed when you move these cases to `overlaps.test`.

2018-12-14 20:18 UTC, midenok commented on mysql-test/suite/period/t/insert_replace.test
> +       on duplicate key update val=3;
Please add comment of ODKU behavior:
```sql
MERGE INTO t USING t
ON id=1 AND s<=2003-04-01 AND e >= 2003-03-01
WHEN MATCHED UPDATE SET val=3
WHEN NOT MATCHED INSERT VALUES (1, 3, '2003-01-01', '2003-04-01');
```

2018-12-14 20:18 UTC, midenok commented on mysql-test/suite/period/t/insert_replace.test
> +       on duplicate key update val=4;
There is no test case when ODKU ...
1. ... inserts a row.
2. ... updates multiple rows.
3. ... updates multiple rows but excludes rows not matched by ID.

2018-12-14 20:18 UTC, midenok commented on mysql-test/suite/period/r/insert_replace.result
> +drop table t;
## Bug 1: multiple rows are not updated.
### Reproduce
```sql
create or replace table t (id int, val int, s date, e date, period for p (s,e), primary key (id, p without overlaps));
insert into t values (1, 1, '2003-01-01', '2003-03-01'), (1, 2, '2003-05-01', '2003-07-01');
insert into t values (1, 3, '2003-01-01', '2003-07-01') on duplicate key update val=3;
select * from t;
```
### Result
```
+----+------+------------+------------+
| id | val  | s          | e          |
+----+------+------------+------------+
|  1 |    3 | 2003-01-01 | 2003-03-01 |
|  1 |    2 | 2003-05-01 | 2003-07-01 |
+----+------+------------+------------+
```
### Expected
Second range must be updated too:
```
+----+------+------------+------------+
| id | val  | s          | e          |
+----+------+------------+------------+
|  1 |    3 | 2003-01-01 | 2003-03-01 |
|  1 |    3 | 2003-05-01 | 2003-07-01 |
+----+------+------------+------------+
```
Check it with:
```sql
create or replace table t (id int, val int, s date, e date, period for p (s,e), primary key (id, p without overlaps));
insert into t values (1, 2, '2003-05-01', '2003-07-01');
insert into t values (1, 3, '2003-01-01', '2003-07-01') on duplicate key update val=3;
select * from t;
+----+------+------------+------------+
| id | val  | s          | e          |
+----+------+------------+------------+
|  1 |    3 | 2003-05-01 | 2003-07-01 |
+----+------+------------+------------+
```

2018-12-14 20:18 UTC, midenok commented on mysql-test/suite/period/r/insert_replace.result
> +drop table t;
## Bug 2: upper bound is ignored
### Reproduce
```sql
create or replace table t (id int, val int, s date, e date, period for p (s,e), primary key (id, p without overlaps));
insert into t values (1, 2, '2003-05-01', '2003-07-01');
insert into t values (1, 3, '2003-07-01', '2003-08-01') on duplicate key update val= 3;
select * from t;
```
### Result
```
+----+------+------------+------------+
| id | val  | s          | e          |
+----+------+------------+------------+
|  1 |    2 | 2003-05-01 | 2003-07-01 |
|  1 |    3 | 2003-07-01 | 2003-08-01 |
+----+------+------------+------------+
```
### Expected
```
+----+------+------------+------------+
| id | val  | s          | e          |
+----+------+------------+------------+
|  1 |    3 | 2003-05-01 | 2003-07-01 |
|+----+------+------------+------------+
```

According to formula:
```sql
MERGE INTO t USING t
ON id = insert_id AND s<= insert_e AND e >= insert_s
WHEN MATCHED UPDATE SET val=3
WHEN NOT MATCHED INSERT VALUES (1, 3, '2003-01-01', '2003-04-01');
```
inserted record matches the above conditions.

2018-12-14 20:18 UTC, midenok commented on mysql-test/suite/period/r/insert_replace.result
> +drop table t;
## Bug 3: wrong "rows affected" counter
### Reproduce
```sql
create or replace table t (id int, val int, s date, e date, period for p (s,e), primary key (id, p without overlaps));
insert into t values (1, 1, '2003-01-01', '2003-03-01'), (1, 2, '2003-05-01', '2003-07-01');
insert into t values (1, 3, '2003-01-01', '2003-02-01') on duplicate key update val=3;
```
### Result
```
Query OK, 2 rows affected (0.005 sec)
```
### Expected
```
Query OK, 1 rows affected (0.005 sec)
```
Last INSERT affects only one row.

2018-12-15 19:15 UTC, midenok commented
Full test fails:
```
Completed: Failed 83/4440 tests, 98.13% were successful.

Failing test(s): rpl.rpl_plugin_load rpl.rpl_table_options mariabackup.undo_space_id main.bootstrap mariabackup.absolute_ibdata_paths innodb.innodb_simulate_comp_failures mariabackup.incremental_encrypted mariabackup.full_backup mariabackup.incremental_backup mariabackup.small_ibd mariabackup.xbstream mariabackup.mdev-14447 mariabackup.xb_file_key_management mariabackup.xb_compressed_encrypted mariabackup.xb_fulltext_encrypted mariabackup.binlog mariabackup.lock_ddl_per_table mariabackup.partition_datadir mariabackup.xb_partition mariabackup.innodb_log_optimize_ddl mariabackup.skip_innodb mariabackup.apply-log-only mariabackup.apply-log-only-incr mariabackup.backup_ssl mariabackup.create_during_backup mariabackup.create_with_data_directory_during_backup mariabackup.data_directory mariabackup.drop_table_during_backup mariabackup.extra_lsndir mariabackup.incremental_ddl_during_backup mariabackup.log_checksum_mismatch mariabackup.missing_ibd mariabackup.mlog_index_load mariabackup.partial mariabackup.partial_exclude mariabackup.recreate_table_during_backup mariabackup.rename_during_backup mariabackup.rename_during_mdl_lock mariabackup.system_versioning mariabackup.truncate_during_backup mariabackup.unsupported_redo mariabackup.xb_history mariabackup.xb_page_compress main.partition_example main.plugin_load main.plugin_load_option disks.disks main.plugin_maturity main.plugin main.plugin_not_embedded main.table_options-5867 main.truncate_badse main.blackhole_plugin plugins.auth_ed25519 main.partition_explicit_prune main.mysql_upgrade_noengine main.plugin_innodb
```

2019-03-22 09:36 UTC, midenok commented
What is the status of this PR? Please fix.

2019-05-29 11:18 UTC, FooBarrior commented
### No race condition
Guarding unlock(dict_operation_lock) + lock(MDL) does not help
```diff
Index: storage/innobase/handler/ha_innodb.cc
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- storage/innobase/handler/ha_innodb.cc	(revision 651a43e0a0361098c35164a128ca588a2989d8e1)
+++ storage/innobase/handler/ha_innodb.cc	(date 1559123117000)
@@ -20598,6 +20598,8 @@
 	goto retry_mdl;
 }
 
+mysql_mutex_t MEGA_MUTEX;
+
 /** Find or open a table handle for the virtual column template
 @param[in]	thd	thread handle
 @param[in,out]	table	InnoDB table whose virtual column template
@@ -20611,8 +20613,12 @@
 		/* Purge thread acquires dict_operation_lock while
 		processing undo log record. Release the dict_operation_lock
 		before acquiring MDL on the table. */
+		// TODO: lock
+		mysql_mutex_lock(&MEGA_MUTEX);
 		rw_lock_s_unlock(dict_operation_lock);
-		return innodb_acquire_mdl(thd, table);
+		auto res = innodb_acquire_mdl(thd, table);
+		mysql_mutex_unlock(&MEGA_MUTEX);
+		return res;
 	} else {
 		if (table->vc_templ->mysql_table_query_id
 		    == thd_get_query_id(thd)) {
Index: sql/mdl.cc
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- sql/mdl.cc	(revision 651a43e0a0361098c35164a128ca588a2989d8e1)
+++ sql/mdl.cc	(date 1559122409000)
@@ -2262,12 +2262,14 @@
 
   my_qsort(sort_buf, req_count, sizeof(MDL_request*),
            mdl_request_ptr_cmp);
-
+  extern mysql_mutex_t MEGA_MUTEX;
+  mysql_mutex_lock(&MEGA_MUTEX);
   for (p_req= sort_buf; p_req < sort_buf + req_count; p_req++)
   {
     if (acquire_lock(*p_req, lock_wait_timeout))
       goto err;
   }
+  mysql_mutex_unlock(&MEGA_MUTEX);
   my_free(sort_buf);
   DBUG_RETURN(FALSE);
 
@@ -2284,6 +2286,7 @@
   {
     (*p_req)->ticket= NULL;
   }
+  mysql_mutex_unlock(&MEGA_MUTEX);
   my_free(sort_buf);
   DBUG_RETURN(TRUE);
 }
Index: sql/mysqld.cc
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- sql/mysqld.cc	(revision 651a43e0a0361098c35164a128ca588a2989d8e1)
+++ sql/mysqld.cc	(date 1559123008000)
@@ -2410,6 +2410,8 @@
   mysql_cond_destroy(&COND_start_thread);
   mysql_cond_destroy(&COND_flush_thread_cache);
   mysql_mutex_destroy(&LOCK_server_started);
+  extern mysql_mutex_t MEGA_MUTEX;
+  mysql_mutex_destroy(&MEGA_MUTEX);
   mysql_cond_destroy(&COND_server_started);
   mysql_mutex_destroy(&LOCK_prepare_ordered);
   mysql_cond_destroy(&COND_prepare_ordered);
@@ -4861,6 +4863,8 @@
   mysql_mutex_init(key_LOCK_server_started,
                    &LOCK_server_started, MY_MUTEX_INIT_FAST);
   mysql_cond_init(key_COND_server_started, &COND_server_started, NULL);
+  extern mysql_mutex_t MEGA_MUTEX;
+  mysql_mutex_init(0, &MEGA_MUTEX, MY_MUTEX_INIT_FAST);
   sp_cache_init();
 #ifdef HAVE_EVENT_SCHEDULER
   Events::init_mutexes();
```

2019-05-30 14:26 UTC, midenok commented
What is the status of this task? Are comments fixed?

2019-11-14 13:20 UTC, FooBarrior commented on mysql-test/suite/period/r/insert_replace.result
> +drop table t;
It's `info.copied + info.deleted + ((some_capabilities) ?  info.touched : info.updated)`, so I don't think so. See `my_ok` call in `myslq_insert`

2019-11-14 13:28 UTC, FooBarrior commented on sql/sql_insert.cc
> +        error= table->file->ha_rnd_pos(table->record[1], table->file->dup_ref);
Yes, from the distance of passed year I can see, that I have probably mixed key reading changes with key_buffer refactoring. I will try to move it to the separate commit

2019-11-14 13:29 UTC, FooBarrior commented on mysql-test/suite/period/t/insert_replace.test
> +drop table t;
I want to do it on the very latest stage, if possible. It is very comfortable to test and fix issues in a separate file

2019-11-14 13:31 UTC, FooBarrior commented on mysql-test/suite/period/t/insert_replace.test
> +       on duplicate key update val=3;
added this note. the new changes are on https://github.com/MariaDB/server/commits/nm/replace

2019-11-14 13:32 UTC, FooBarrior commented on mysql-test/suite/period/r/insert_replace.result
> +drop table t;
Bug 1,2: thanks, fixed.
https://github.com/MariaDB/server/commits/nm/replace

2019-11-14 13:32 UTC, FooBarrior commented
all the foregoing changes are on https://github.com/MariaDB/server/commits/nm/replace

2019-11-14 13:32 UTC, closed without merging