ek/optimized select
tempesta-tech/mariadb pull request #70
Opened 2016-11-04 04:54 UTC by kevgs

2016-11-04 05:22 UTC, midenok commented on sql/sql_select.cc
> +static bool replace_optimized_fields_with_nulls(THD *thd, List<Item> &item_list,
Wny such long function names? No notion that it belongs to system versioning.

2016-11-04 05:22 UTC, midenok commented on sql/sql_select.cc
> +  bool replaced_some_unversioned_field= false;
Inconsistency: many terms for same meaning. Too long variable name. There is no sence in reading whole sentences just to read variable name.

2016-11-04 05:23 UTC, midenok commented on sql/sql_select.cc
> +                        ER_NON_VERSIONED_FIELD_IN_VERSIONED_QUERY,
Again inconsistency.

2016-11-04 05:24 UTC, midenok commented on sql/sql_select.cc
> +
Garbage chunk.

2016-11-07 19:03 UTC, kevgs commented
Pushed a new code. Warnings work and printed no more then once.

2016-11-07 19:35 UTC, midenok commented on sql/item.cc
> +    {
Why `parent_lex->thd` can be **null** when `parent_lex` not?

2016-11-07 19:37 UTC, midenok commented on sql/item.cc
> +      if (!context->select_lex->optimized_in_versioned)
Extra `if` instead of `&&`.

2016-11-07 19:40 UTC, midenok commented on sql/share/errmsg-utf8.txt
> +        eng "Use of non-versioned field in versioned query"
"Attempt to read unversioned field in historical query"

2016-11-07 19:46 UTC, midenok commented on sql/item.cc
> +    field->force_null= true;
If `force_null` was `false` print warning. No need in extra flag.

2016-11-07 19:49 UTC, midenok commented on sql/item.cc
> +  if (field && context && context->select_lex &&
Again, why you check `field` if code before asserts it is **non-null**. Remove all needless conditions!

2016-11-07 19:51 UTC, midenok requested changes
Needless conditions.

2016-11-08 10:01 UTC, kevgs commented
Pushed new code.

2016-11-08 10:22 UTC, midenok approved these changes

2016-11-08 10:23 UTC, midenok commented
Add **SQL: ** prefix to commit message and *Rebase and merge*.

2016-11-08 10:28 UTC, midenok commented on sql/item.cc
> +    field->force_null= true;
Add
```c++
DBUG_ASSERT(context && context->select_lex && context->select_lex->parent_lex && contex->select_lex->parent_lex->thd);
```

2016-11-08 10:31 UTC, midenok commented on sql/item.cc
> +
```c++
DBUG_ASSERT(context && context->select_lex);
```

2016-11-08 10:33 UTC, midenok commented on sql/item.cc
> +                contex->select_lex->parent_lex->thd);
```c++
DBUG_ASSERT(context->select_lex->parent_lex && contex->select_lex->parent_lex->thd);
```

2016-11-08 11:35 UTC, merged