ek/reprint
tempesta-tech/mariadb pull request #75
Opened 2016-11-13 15:41 UTC by kevgs

2016-11-14 05:11 UTC, midenok commented
Add **closes** clause.

2016-11-14 05:33 UTC, midenok requested changes

2016-11-14 05:33 UTC, midenok commented on BUILD/capture_warnings.sh
> +TMP_FILE=/tmp/compile.warning
Wrong usage of fixed file name in **/tmp**. Use `mktemp`. Use **/dev/shm** to utilize tmpfs. `TMP_FILE` is not needed (see below).

2016-11-14 05:33 UTC, midenok commented on BUILD/capture_warnings.sh
> +$@ 2> $TMP_FILE
1. Use this technique to catch `STDERR` to variable:
    ```
    exec 3>&1
    x=$((echo err >&2; echo out) 2>&1 1>&3)
    ```

2. Wrong expansion of `$@`. Use `"$@" instead`.

2016-11-14 05:33 UTC, midenok commented on CMakeLists.txt
> +  "${CMAKE_BINARY_DIR}/compile.warnings")
Where is deletion at compilation start?

2016-11-14 05:33 UTC, midenok commented on sql/CMakeLists.txt
> +  DEPENDS mysqld)
Modification of several `CMakeLists.txt` is highly unwanted. P.1 of task is not done.

2016-11-15 18:55 UTC, kevgs commented
I failed with 'exec 3>&1' trick and used something else.

2016-11-16 06:13 UTC, midenok commented on BUILD/capture_warnings.sh
> +x=$(("$@") 2>&1 | tee /dev/stderr)
Does this work correctly?

2016-11-16 08:01 UTC, midenok commented on BUILD/capture_warnings.sh
> +x=$(("$@") 2>&1 | tee /dev/stderr)
Use:
```bash
exec 3>&1
 x=$((echo err >&2; echo out) 2>&1 1>&3)
echo "$x" >&2
```
Rename `x` to `cmderr`.

2016-11-16 08:02 UTC, midenok commented on BUILD/capture_warnings.sh
> +    echo "$x" >> $warn_file
echo -n

2016-11-16 08:03 UTC, midenok commented on BUILD/capture_warnings.sh
> +error=${pipestatus}
PIPESTATUS

2016-11-16 08:06 UTC, midenok commented on CMakeLists.txt
> +IF (CMAKE_BUILD_TYPE MATCHES "Debug")
Can it be under single IF condition?

2016-11-16 08:27 UTC, midenok commented on CMakeLists.txt
> +    DEPENDS mysql udf_example explain_filename-t
DEPENDS REMOVE_WARNINGS_FILE

2016-11-16 09:29 UTC, merged